server/src/main/java/com/onetool/server/TestDataLoader.java, server/src/main/java/com/onetool/server/blueprint/Blueprint.java, server/src/main/java/com/onetool/server/blueprint/BlueprintRepository.java, server/src/main/java/com/onetool/server/blueprint/BlueprintService.java, server/src/main/java/com/onetool/server/blueprint/SearchController.java, server/src/main/java/com/onetool/server/category/FirstCategoryType.java, server/src/main/java/com/onetool/server/order/OrderBlueprint.java, server/src/main/resources/application.properties, server/src/main/resources/data.sql, server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
1. 빌딩 카테고리 검색
- FirstCategoryType을 이용하여 1차 카테고리 enum화
- 저장된 카테고리를 이용하여 1차 카테고리 검색 비즈니스 로직 구현
1. 키워드 기반 검색 엔드포인트 변경
- /search에서 /blueprint로 변경
2. OrderBlueprint에 Blueprint 필드가 두 개인 문제 해결
=> feat: 1차카테고리 검색 / fix: OrderBlueprint 필드 수정

server/src/main/java/com/onetool/server/global/exception/BaseException.java, server/src/main/java/com/onetool/server/global/exception/BaseResponse.java, server/src/main/java/com/onetool/server/global/exception/WebErrorController.java, server/src/main/java/com/onetool/server/global/exception/codes/BaseCode.java, server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java, server/src/main/java/com/onetool/server/global/exception/codes/SuccessCode.java, server/src/main/java/com/onetool/server/global/exception/codes/reason/Reason.java, server/src/main/java/com/onetool/server/global/exception/howToUse/TempController.java, server/src/main/java/com/onetool/server/global/exception/howToUse/service/TempService.java, server/src/main/java/com/onetool/server/global/exception/howToUse/service/TempServiceImpl.java, server/src/main/java/com/onetool/server/global/exception/howToUse/temp/TempConverter.java, server/src/main/java/com/onetool/server/global/exception/howToUse/temp/TempRequest.java, server/src/main/java/com/onetool/server/global/exception/howToUse/temp/TempResponse.java, server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java, server/src/main/java/com/onetool/server/global/handler/MyExceptionHandler.java
global exception 및 api 응답 형식 통일
모든 http 요청에 대해 응답을 200 ok로 처리하고 응답 메세지 안에 성공 혹은 실패 관련 스토리를 적는다.
{
"isSuccess": true 또는 false,
"code": "에러 코드 혹은 성공 코드",
"message": "에러 메세지 혹은 성공 메세지"
"result" : "success 시 반환해야 할 문자열이나 데이터들을 여기다가 넣으면 됨"
}
중요한 것은 success는 반드시 result에 값이 있어야 함.(성공 메세지랑 성공 시 result 안에 넣은 메세지는 다른 것 )
ex.
{
"isSuccess": true,
"code": "SUCCESS-0000",
"message": "요청에 성공하였습니다.",
"result": "로그인에 성공했습니다."
}
{
"isSuccess": false,
"code": "BINDING-0000",
"message": "이메일을 형식에 맞게 다시 입력해주세요."
}
사용 방법은 global/exception/howToUse에 있는 컨트롤러와 서비스를 참고해주세요
서비스에서 생길 수 있는 예외들을 생각하고 그런 오류들은 ErrorCode에 만들어 주세요
=> [feat] global exception 및 api 응답 형식 통일

server/build.gradle, server/src/main/java/com/onetool/server/global/auth/jwt/JwtUtil.java, server/src/main/java/com/onetool/server/global/config/SecurityConfig.java, server/src/main/java/com/onetool/server/global/oauth2/CustomOAuth2User.java, server/src/main/java/com/onetool/server/global/oauth2/OAuthAttributes.java, server/src/main/java/com/onetool/server/global/oauth2/handler/OAuth2LoginFailureHandler.java, server/src/main/java/com/onetool/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java, server/src/main/java/com/onetool/server/global/oauth2/service/CustomOAuth2UserService.java, server/src/main/java/com/onetool/server/global/oauth2/userinfo/GoogleOAuth2UserInfo.java, server/src/main/java/com/onetool/server/global/oauth2/userinfo/OAuth2UserInfo.java, server/src/main/java/com/onetool/server/member/DateTimeFormat.java, server/src/main/java/com/onetool/server/member/Member.java, server/src/main/java/com/onetool/server/member/MemberController.java, server/src/main/java/com/onetool/server/member/MemberRepository.java, server/src/main/java/com/onetool/server/member/MemberService.java, server/src/main/java/com/onetool/server/member/SSOTestController.java, server/src/main/java/com/onetool/server/member/SocialType.java, server/src/main/java/com/onetool/server/member/UserRole.java, server/src/main/java/com/onetool/server/member/dto/MemberCreateRequest.java, server/src/main/java/com/onetool/server/member/dto/MemberCreateResponse.java, server/src/main/resources/templates/login.html, server/src/test/java/com/onetool/server/member/MemberServiceTest.java
[ SSO 관련 파일 설명 ]
OAuth2LoginFailureHandler : SSO 로그인 실패 시 핸들러
OAuth2LoginSuccessHandler : SSO 로그인 성공 시 핸들러
CustomOAuth2UserService : Resource Server에서 받아온 정보를 DB에 저장, OAuth2User에 로그인 정보 저장
CustomOAuth2User : DefaultOAuth2User를 상속받아 SSO 로그인된 유저 정보를 저장
OAuthAttributes : 각 SSO에서 받아오는 데이터가 다르므로,SSO 별로 받는 데이터를 분기 처리하는 DTO 클래스
SocialType : SSO enum 클래스
SSOTestController : SSO 테스트를 위한 컨틀로러로 login.html로 이동
login.html : SSO 로그인을 확인하기 위한 트리거 제공하는 동적 페이지
<br/>
- 일반 회원가입 구현
- 일반 로그인과의 충돌 테스트
<br/>
- [레포 이름 #이슈번호](이슈 주소)
<br/>
=> feat: 구글 SSO 로그인

server/build.gradle, server/src/main/java/com/onetool/server/global/auth/CustomAuthenticationEntryPoint.java, server/src/main/java/com/onetool/server/global/auth/MemberAuthContext.java, server/src/main/java/com/onetool/server/global/auth/filter/JwtAuthFilter.java, server/src/main/java/com/onetool/server/global/auth/jwt/JwtUtil.java, server/src/main/java/com/onetool/server/global/auth/login/service/CustomUserDetailsService.java, server/src/main/java/com/onetool/server/member/controller/SSOTestController.java, server/src/main/java/com/onetool/server/member/dto/MemberCreateRequest.java, server/src/main/java/com/onetool/server/member/service/MemberService.java
- GSON의 버그로 인해 Jwt의 Claim에 Long 값을 넣으면, Double로 변환되어 저장됨.
- 이를 명시적 형변환을 통해 해결
<br/>
<br/>
- [레포 이름 #이슈번호](이슈 주소)
<br/>
=> fix: PrincipalDetail에 로그인 유저가 저장되지 않는 버그 수정

server/src/main/java/com/onetool/server/global/auth/login/OAuthAttributes.java, server/src/test/java/com/onetool/server/category/CategoryServiceTest.java
- CategoryServiceTest에 테스트 통과
- SSO 로그인 시, PlatformType을 SSO로 지정
- Member의 `PlatformType` : **SSO 회원과 일반회원 구분**
- Member의 'SocialType' : **SSO의 플랫폼 구분**
<br/>
<br/>
<br/>
=> test: 모든 카테고리의 도면 검색 테스트 / fix: SSO 로그인 시, PlatformType을 SSO로 지정

server/src/main/java/com/onetool/server/global/config/SecurityConfig.java, server/src/main/java/com/onetool/server/mail/MailService.java, server/src/main/java/com/onetool/server/member/controller/MemberController.java, server/src/main/java/com/onetool/server/member/dto/MemberFindPwdRequest.java, server/src/main/java/com/onetool/server/member/service/MemberService.java
- 비밀번호 찾기 시, 가입 시 입력한 이메일로 비밀번호를 발송
- 현재 암호화된 비밀번호를 발송하도록 구현됨.
- 추후, 비밀번호 변경 기능 구현 시 임시 비밀번호 발급
<br/>
- 비밀번호 변경 구현
- 랜덤 비밀번호 생성 및 발송 로직 수정
<br/>
- [레포 이름 #이슈번호](이슈 주소)
<br/>
=> feat: 비밀번호 찾기 이메일 발송 구현 (임시)

server/src/main/java/com/onetool/server/member/dto/MemberFindEmailRequest.java, server/src/main/java/com/onetool/server/member/dto/MemberSimpleInfoDto.java, server/src/main/java/com/onetool/server/member/dto/MemberUpdateRequest.java
- 업데이트의 경우, 변경된 값만 받으면 되기 때문에 https://github.com/NotNull 등의 Valid는 불필요하다 판단
- chore: 이메일찾기 DTO, 유저 간단 정보 DTO
<br/>
<br/>
<br/>
=> fix: MemberUpdateRequest의 필드에 Valid 제거

server/src/main/java/com/onetool/server/member/controller/MemberController.java, server/src/main/java/com/onetool/server/member/domain/Member.java, server/src/main/java/com/onetool/server/member/dto/MemberFindEmailRequest.java, server/src/main/java/com/onetool/server/member/dto/MemberInfoResponse.java, server/src/main/java/com/onetool/server/member/repository/MemberRepository.java, server/src/main/java/com/onetool/server/member/service/MemberService.java, server/src/main/java/com/onetool/server/order/Orders.java, server/src/test/java/com/onetool/server/member/MemberServiceTest.java
-  회원 정보 조회 기능 
- 이메일 찾기를 피그마를 기반으로 이름,전화번호를 사용하도록 수정함 
<br/>
<br/>
<br/>
=> feat: 회원 정보 조회/refactor: 이름과 전화번호를 통한 이메일 찾기

server/src/main/java/com/onetool/server/member/controller/MemberController.java, server/src/main/java/com/onetool/server/member/domain/Member.java, server/src/main/java/com/onetool/server/member/service/MemberService.java, server/src/test/java/com/onetool/server/member/MemberServiceTest.java
- 유저정보 수정을 기존의 `Putmapping`에서 `PatchMapping`로 수정함
- 유저정보 수정시 cart id에 대한 충돌이 발생해 `this.cart = cart != null ? cart : Cart.createCart(this);`로 수정함 
<br/>
- 우선 email도 /user를 통해 수정하도록 구현해두었으나 유저의 id를 email로 사용함
- 이를 변경이 가능하게 하도록하는게 맞는 것인지
<br/>
<br/>
=> refactor: @PatchMapping를 통해서 개인정보 수정하도록 변경

server/src/main/java/com/onetool/server/member/service/MemberService.java
TIC-85
- 이메일 찾기 중 존재하지 않는 회원 정보의 경우, MemberNotFoundException 던지도록 수정
- 기존 RuntimeException에서 수정
<br/>
- 카테고리, 검색어 검색 기능 ApiResponse를 이용한 리펙터링
<br/>
<br/>
=> [TIC-85] fix: 이메일 찾기 중 존재하지 않는 회원 정보 Exception 수정

server/src/main/java/com/onetool/server/DataLoader.java, server/src/main/java/com/onetool/server/blueprint/controller/SearchController.java, server/src/main/java/com/onetool/server/blueprint/service/BlueprintService.java
TIC-92
- Controller에서 if-else를 이용한 null 구분을 Service에서 처리하도록 수정
- 기존에 else문을 삭제하고 return을 사용하도록 수정
- 기존 findAllByfirstCategory와 findAllBySecondCateogry를 private으로 전환.
- 새로운 findAllCategory를 사용하여 2차 카테고리 null 구분 후, 알맞은 메서드 선택
- 기존 ?을 반환 타입에 맞게 구체적으로 수정
<br/>
- refresh Token 구현
<br/>
[PR#49](https://github.com/likelion-onetool/backend/pull/49)
<br/>
=> [TIC-92] 카테고리 Controller와 Service 리팩터링

server/src/main/java/com/onetool/server/cart/controller/CartController.java, server/src/main/java/com/onetool/server/cart/dto/CartRequest.java, server/src/main/java/com/onetool/server/member/controller/MemberController.java, server/src/main/java/com/onetool/server/member/repository/MemberRepository.java, server/src/main/java/com/onetool/server/member/service/MemberService.java, server/src/main/java/com/onetool/server/qna/controller/QnaBoardController.java, server/src/main/java/com/onetool/server/qna/controller/QnaReplyController.java, server/src/main/java/com/onetool/server/qna/dto/response/QnaBoardResponse.java, server/src/main/java/com/onetool/server/qna/dto/response/QnaReplyResponse.java, server/src/main/java/com/onetool/server/qna/service/QnaBoardServiceImpl.java
TIC-95 내가 문의한 내역 조회
- feat : 내 문의사항 조회 기능 추가
> PrincipalDetails를 기반으로 Member를 조회할 때 하나의 select 쿼리에 해당 멤버가 작성한 문의사항 글까지 함께 가져오도록 fetch join 진행( @ OneToMany는 기본이 지연로딩)
- refactor : CartController, QnaBoardController, QnaReplyController 컨벤션 통일. 정적 팩토리 메서드 명 from으로 통일
- chore : QnaBoardBriefResponse에서 Member의 QnaBoard List를 가져오면 스트림으로 각 요소를 QnaBoardBriefResponse로 변환하는 정적 팩토리 메서드 추가
<br/>
- 성능 최적화 : N+1, 페이징 성능 고려 (데이터가 적어 페이징 성능은 그냥 무시할깨 생각 중)
<br/>
<br/>
=> 🎟️ [TIC-95] feat : 내 문의사항 조회 기능 추가

server/src/main/java/com/onetool/server/ServerApplication.java, server/src/main/java/com/onetool/server/blueprint/controller/BlueprintController.java, server/src/main/java/com/onetool/server/blueprint/service/BlueprintInspectionService.java, server/src/main/java/com/onetool/server/blueprint/service/BlueprintRefreshService.java, server/src/main/java/com/onetool/server/blueprint/service/BlueprintService.java, server/src/main/java/com/onetool/server/global/exception/BlueprintNotApprovedException.java, server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java, server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
TIC-101
TIC-102
- '/blueprint/{id}'로 접근시 기존의 `findBlueprintById`를 통해 id를 조회하는 방식에서 `findApprovedBlueprintById`를 통해 InspectionStatus.PASSED 검증 후, PASSED 상태인 도면만 상세페이지 조회 가능
- `BlueprintNotApprovedException`를 통해서 승인 받지 않은 도면에 접근시 403에러
[[TIC-102] 도면 조회 시 검수 완료된 도면만 불러오도록 변경](https://github.com/likelion-onetool/backend/commit/c36ef6cfed7a0940d80de00aeddcb725293106cc) 
- `@EnableScheduling` 어노테이션을 추가
- `@Scheduled`를 통해서 매일 자정 새로고침,  매일 자정에 PASSED 상태인 도면을 조회
[[TIC-101] 자정마다 검수가 완료된 도면 새로고침 하도록 구현](https://github.com/likelion-onetool/backend/commit/355c16d64a54862d168576e1d8a4edb6ea46513b) 
<br/>
- 매일 자정에 PASSED 상태인 도면을 조회 하는 것만 우선 구현, 조회 후의 진행할 로직 추가 
- 새로고침에 대한 실제 test 
- 상품 id를 통한 상세 조회 외 검색할 때도 다 승인 받지 않은 도면 거를지? 
<br/>
<br/>
=> [TIC-101,102] feat: 자정마다 검수가 완료된 도면 새로고침 구현/ 검수 완료된 도면만 불러오도록 수정

server/build.gradle, server/src/main/java/com/onetool/server/blueprint/controller/BlueprintUploadController.java, server/src/main/java/com/onetool/server/blueprint/dto/BlueprintUploadRequest.java, server/src/main/java/com/onetool/server/blueprint/dto/BlueprintUploadResponse.java, server/src/main/java/com/onetool/server/blueprint/service/BlueprintS3UploadService.java, server/src/main/java/com/onetool/server/global/config/S3Config.java, server/src/main/java/com/onetool/server/global/config/SecurityConfig.java, server/src/main/java/com/onetool/server/global/exception/WebErrorController.java, server/src/main/java/com/onetool/server/global/exception/codes/BaseCode.java, server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java, server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
TIC-100
- 도면 관련 파일 S3 업로드 기능 추가 (단일 파일)
- 도면 업로드에 대한 예외 추가
- S3 Config 추가
- 파일 없이 업로드 요청 시 MultipartException을 ExceptionHandler에서 처리
- 도면 업로드 관련 DTO 생성
- SecurityConfig에서 도면 업로드 api는 유저 인증 거치지 않게 임시로 설정
- URL 오류 시 URL_NON_EXIST 예외 처리
- jdbc dependency 삭제
- aws 및 http 관련 dependency 추가
<br/>
- 도면 업로드 페이지 컴포넌트를 정확히 안 후 api 다시 설계 예정. 지금은 도면, 도면 상세 이미지, 썸네일 등 각기 다른 api로 설정함
- 다중 파일 업로드 구현 예정
- 파일 확장자 제한 로직 추가
- 파일 명 생성 전략 고민 필요
<br/>
=>  🎟️  [TIC-100] 도면, 도면 상세 페이지 이미지 S3에 저장 

server/src/main/java/com/onetool/server/global/redis/service/MailRedisService.java, server/src/main/java/com/onetool/server/global/redis/service/TokenRedisService.java, server/src/main/resources/application.properties
- Mail인증 용 RedisTemplate와 JwtRefreshToken 용 RedisTemplate가 Service에서 정확하게 지정되지 않음.
- `@qualifier`를 통해 각 RedisTemplate을 지정하여 해결
<br/>
- 개발용 더미데이터 지정
- 개발용 서버 생성 및 CI/CD 구축
<br/>
없음
<br/>
=> fix(redis): RedisTemplate 빈 충돌 문제

server/src/test/java/com/onetool/server/member/MemberServiceTest.java
-  blueprintController에 맞춰 `/users`로 api 변경
- "message"가 아니라 "result"를 비교하도록 수정
<br/>
<br/>
[likelion-onetool #83 ](https://github.com/likelion-onetool/backend/issues/83)
<br/>
=> [#83] test(member):회원 삭제 로직 오류 수정 

server/src/main/java/com/onetool/server/global/redis/config/RedisConfig.java
- Docker Redis 컨테이너에 비밀번호를 설정했지만, Spring RedisConfig에 비밀번호가 설정되어 있지않아 발생한 문제
<br/>
<br/>
#75 
<br/>
=> fix(redis): RedisConfig 비밀번호 설정

server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
- Spriong Securty 필터체인에서  authorizeHttpRequests 설정 중 anyRequest 후에 requestMatchers가 있어 에러 발생
```java
.authorizeHttpRequests(authorize -> authorize
.requestMatchers(AUTH_WHITELIST).permitAll()
.anyRequest().authenticated()
.requestMatchers(CorsUtils::isPreFlightRequest).permitAll()
)
```
- requestMatchers 다음에 anyRequest가 오도록 수정
<br/>
<br/>
#93 
<br/>
=> fix(security): anyRequest 후 requestMatchers 설정 문제

server/src/main/java/com/onetool/server/api/member/controller/MemberController.java, server/src/main/java/com/onetool/server/api/member/dto/MemberLoginResponse.java, server/src/main/java/com/onetool/server/global/auth/login/handler/OAuth2LoginSuccessHandler.java
- 기존 Payload에 accessToken과 refreshToken을 같이 보낼 경우, refreshToken에 대한 XSF 공격에 취약합니다.
- `HttpOnly` 옵션을 통한 `쿠키`로 전달할 수 있도록 설정했어요
- 쿠키 만료 기간을 `7일`로 설정
<br/>
<br/>
#98 
<br/>
=> fix: refreshToken 전달 방식 쿠기로 변경

server/src/main/java/com/onetool/server/api/blueprint/controller/SearchController.java
프론트 단에서 전송한 검색어가 UTF-8로 인코딩되어 전송됨. 따라서, 서버 측에서 keyword를 받고 이를 UTF-8로 디코딩하여 사용.
검색어로 검색할 때 예를들어 "평면"을 검색하면
https://test.onetool.co.kr/blueprint?s=%ED%8F%89%EB%A9%B4&page=0&size=8 이런식으로 전송되어 백엔드에서 디코딩이 필요함.
<br/>
<br/>
#98 
<br/>
=> fix(search): 검색어 URL 디코딩 추가

server/src/main/java/com/onetool/server/api/blueprint/controller/BlueprintInspectionController.java, server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintInspectionService.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintRefreshService.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java, server/src/test/java/com/onetool/server/blueprint/BlueprintInspectionTest.java
- `findByInspectionStatus`는 **List<>** 대신 `Page<>`를 반환하도록 수정
- 기존 blueprint refresh 로직에서 List<>를 사용한다. 위 메서드를 통해 반환받은 Page를 `Page<>.getContent`를 통해 List 변환하여 사용하도록 수정
<br/>
<br/>
#96 
<br/>
=> fix(blueprint): 검수여부에 따른 전체 도면 검색 기능 수정 

server/src/main/java/com/onetool/server/api/member/enums/SocialType.java, server/src/main/java/com/onetool/server/global/auth/login/OAuthAttributes.java, server/src/main/java/com/onetool/server/global/auth/login/handler/OAuth2LoginSuccessHandler.java, server/src/main/java/com/onetool/server/global/auth/login/service/CustomOAuth2UserService.java, server/src/main/resources/application.properties
- close #110 
Google OAuth2가 작동하지 않던 문제는 다음과 같았습니다.
1. 과거 사용 중이던 OAuth2 API가 삭제되어 있던 점
2. 리소스 서버로 부터 받아온 정보 중 ID를 추가하지 않아 JWT 토큰이 제대로 생성되지 않던 점
3. 리소스 서버로부터의 정보 중 scope가 설정되어 있지 않아 형변환 오류가 발생했던 점
이 중 1, 2번의 경우 단순히 ID 값 주입 및 submodule 업데이트로 해결했습니다.
3번의 경우, 리소스 서버로 부터 받아오는 정보에 따라 형변환되는 객체가 달라짐에 따라 발생했습니다.
```java
@Override
public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws IOException, ServletException {
log.info("OAuth2 Login 성공");
try {
PrincipalDetails principalDetails = (PrincipalDetails) authentication.getPrincipal();
MemberAuthContext member = principalDetails.getContext();
// 이하 생략
```
_현재 scope가 설정되어 있지 않은 경우,_ 
제가 만든 `PrincipalDetail`로 Case되지 않고 `DefaultOidcUser`로 Case 돼요.
그 이유는 PrincipalDetail과 …
=> 🔨fix: Google OAuth2 버그 수정

server/src/main/java/com/onetool/server/api/blueprint/controller/BlueprintController.java, server/src/main/java/com/onetool/server/api/blueprint/dto/BlueprintSortRequest.java, server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java, server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
- close #98 
기존에 전체 도면에서만 sort가 되던 것을 categoryId별로 sort가 가능하도록 api를 추가했습니다. 
세부 추가사항은 아래와 같습니다! 
- blueprint categoryId별로 정렬이 가능하도록 GET 요청 추가: /blueprint/{categoryId}/sort
- 전체의 경우 GET : /blueprint/sort
-  PRICE, CREATED_AT, EXTENSION 에 대한 정렬 가능
- sortOrder 파라미터 추가 (오름차순: asc, 내림차순: desc)
- sortOrder가 null일 경우 기본값은 오름차순(asc)으로 처리
- 가격 정렬 시  salePrice가 유효할 경우엔 salePrice, 아닌 경우 standardPrice로 비교하여 정렬
- BlueprintServiceMockTest에 정렬에 대한 test 추가
- category name 을 api 경로로 둘까 생각했었습니다. 그러면 수정해야할 부분이 많아지는 것 같아, 기존 blueprint에 있는 정보인 categoryId별로 정렬이 가능하도록 구현했습니다.  이름으로 두는게 더 나을까요?
그외 코드에 불필요한 부분이 있다면 말해주세요!
[Spring Pageable](https://velog.io/@soluinoon/Spring-Pageable)
[Spring Data JPA를 활용한 데이터 정렬 구현(JPA method & Pageable, Page)](https://velog.io/@kimdy0915/Spring-Data-JPA%EB%A5%BC-%ED%99%9C%EC%9A%A …
=> feat: blueprint categoryId 별로 정렬 기능 추가

server/src/main/java/com/onetool/server/DataLoader.java, server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java, server/src/main/java/com/onetool/server/global/config/SecurityConfig.java, server/src/main/resources/application.properties, server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
- #113 
기존 코드의 경우, 키워드를 통한 Blueprint를 검색하는 JPQL을 사용하고 있다. 이 경우에 당연하게도 Blueprint에 있는 연관관계에 의해 N+1이 발생하게 된다.
```java
// Blueprint
@OneToMany(mappedBy = "blueprint")
private List<OrderBlueprint> orderBlueprints = new ArrayList<>();
@OneToMany(mappedBy = "blueprint")
private List<CartBlueprint> cartBlueprints = new ArrayList<>();
```
```java
// BlueprintRepository
@Query(value = "SELECT b FROM Blueprint b WHERE (b.blueprintName LIKE %:keyword% OR b.creatorName LIKE %:keyword%) AND b.inspectionStatus = :status AND b.isDeleted = false")
Page<Blueprint> findAllNameAndCreatorContaining(@Param("keyword") String keyword, @Param("status") InspectionStatus status, Pageable pageable);
```
현재 기본 값으로 지연 로딩이 설정되어 있다. Blueprint를 조회하게 되면 연관관계를 가진 orderBlueprints와 cartBlueprints를 가져오게 된다. 이 경우, Blueprint의 …
=> refactor: 컬렉션 Fatch Join 쿼리 분리를 통한 N+1 해결

server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
- close #113 
- BlueprintSearchService에 `@Transactional(readOnly=true)` 부여
BlueprintSearch 쿼리들은 조회만을 수행한다. @Transactional(readOnly = true)를 사용하면 아래의 장점이 있다.
영속성 컨텍스트가 Entity 조회 시, 초기 상태의 Snapshot으로 저장한다. 트랜잭션 commit 시, Snapshot과 Entity 상태를 비교하여 변경된 내용에 대한 update Query를 생성해 쓰기 지연 저장소에 저장한다. 일괄적으로 쓰기 지연 저장소의 query들을 flush()하고, 트랜잭션을 commit()하여 entity의 수정이 이루어진다. 이를 `Dirty Checking`라고 한다.
readOnly =true 시, JPA의 세션 플러시 모드를 MANUAL로 수정한다. 이는 사용자가 수동으로 FLUSH 해야만 변경사항이 Entity에 반영되도록한다. 따라서, Snapshot을 생성하지 않아 **메모리 절약 가능하다.**
쉽게 말해 readOnly로 트랜잭션 실행 시, 해당 트랜잭션 영역에 대한 쓰기 작업이 비활성화 되기 때문에 무결성을 보장할 수 있다. 이와 관련하여 더 조사를 하면서 인상적인 사실을 알 수 있었다.
> [!TIP]
>  `OSIV(Open Session In View)` : 영속성 컨텍스트를 View Layer까지 유지하는 속성으로, 클라이언트의 요청 시점부터 영속성 컨텍스트를 생성하여 Filter / Interceptor - Controller에서 영속성 컨텍스트가 생성되어 View …
=> refactor: BlueprintSearchService에 읽기 전용 트랜잭션 부여

server/src/main/java/com/onetool/server/api/member/controller/MemberController.java, server/src/main/java/com/onetool/server/global/redis/controller/TokenController.java
- accessToken을 Body에 전송
- close #119 
1. 프론트엔드 팀의 요청에 따라 AccessToken 전달 방식을 변경
- 기존 Authorization 헤더 대신 Body에 담아 전송
2. API 명세서 수정 (23번, 46번)
=> fix: 로그인, RefreshToken 재발급 토큰 전달 방식 수정

server/src/main/java/com/onetool/server/api/blueprint/controller/BlueprintController.java, server/src/main/java/com/onetool/server/api/member/controller/MemberController.java, server/src/main/java/com/onetool/server/api/member/service/MemberService.java, server/src/main/java/com/onetool/server/global/auth/jwt/JwtUtil.java, server/src/main/java/com/onetool/server/global/exception/IllegalLogoutMember.java, server/src/main/java/com/onetool/server/global/exception/MemberNotFoundException.java, server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java, server/src/main/java/com/onetool/server/global/redis/config/RedisConfig.java, server/src/main/java/com/onetool/server/global/redis/service/TokenBlackListRedisService.java, server/src/main/java/com/onetool/server/global/redis/service/TokenRedisService.java
- close #123 
로그아웃 요청 시, 요청된 accessToken을 남은 기간동안 BlackList에 등재하고 RefreshToken을 Redis에서 삭제됩니다.
로그아웃된 accessToken은 사용할 수 없도록 유효기간을 TTL로 설정하여, 해당 Redis에 저장된 경우 사용할 수 없도록 구현했어요.
현재 **총 3개의 Redis 데이터베이스**를 사용하고 있어요.
| 순서 | {키, 값} | 사용 목적 |
|---|---|---|
| 1 | {email, refreshToken} | 토큰 재발급 시, 토큰 유효성 검사 |
| 2 | {email, 인증코드} | 이메일 인증을 위한 인증코드 저장 |
| 3 | {accessToken, "BlackList"} | 로그아웃된 accessToken 사용 방지 |
Redis 사용에 대한 Wiki를 추가로 남겨보겠습니다.
또한, Redis 데이터베이스를 조회할 수 있는 명령어도 남겨봐요.
```bash
redis-cli -n 1
keys *
```
커스텀 예외 중 BaseException을 상속받지 않아 모든 에러가 StackTrace되는 문제가 있어요. 또한 커스텀 예외 계층화를 통한 ControllerAdvice의 코드를 줄이는 과정도 필요해보여요!
관련된 PR 링크도 남겨봅니다.
[커스텀 예외 리펙터링 PR](https://github.com/ICT-Dev-Route/Dev-Route-BE/pull/140)
[Redis BlackList 구현](https://velog.io/@ch0jm/lnwfrngd)
[로그아웃 …
=> feat: 로그아웃 구현

server/src/main/java/com/onetool/server/api/blueprint/controller/SearchController.java, server/src/main/java/com/onetool/server/api/blueprint/dto/BlueprintSortRequest.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java, server/src/main/java/com/onetool/server/api/category/FirstCategoryType.java, server/src/main/java/com/onetool/server/global/exception/CategoryNotFoundException.java, server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java, server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java, server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
- close #98
- 
- 기존에 `categoryId`를 통해 카테고리별 정렬을 하던 것에서 `categoryName`을 통해 정렬 가능하도록 구현
- `FirstCategoryType` 에 categoryId 추가 수정 
-`BlueprintSearchController`에서 categoryName을 입력받는다. `BlueprintService`에서 categoryName을 통해 도면에 저장된 categoryId를 찾는다. 해당되는 도면에 대한 정렬을 반환한다.
- 문제가 있는 부분 알려주세요! 
+) `BlueprintServiceMockTest` ` @DisplayName("새 blueprint가 정상적으로 생성되는지 확인")` 같이 로그인 인증이 필요한 테스트들이 403 오류 발생, 수정해야함
=> refator: CategoryName별로 정렬 기능

server/build.gradle, server/src/main/java/com/onetool/server/api/payments/controller/PaymentController.java, server/src/main/java/com/onetool/server/api/payments/domain/PaymentProperties.java, server/src/main/java/com/onetool/server/api/payments/domain/TossPayment.java, server/src/main/java/com/onetool/server/api/payments/domain/TossPaymentMethod.java, server/src/main/java/com/onetool/server/api/payments/domain/TossPaymentStatus.java, server/src/main/java/com/onetool/server/api/payments/dto/PaymentErrorResponse.java, server/src/main/java/com/onetool/server/api/payments/dto/SaveAmountRequest.java, server/src/main/java/com/onetool/server/api/payments/repository/PaymentRepository.java, server/src/main/java/com/onetool/server/api/payments/service/PaymentService.java, server/src/main/java/com/onetool/server/global/config/SecurityConfig.java, server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java, server/src/main/resources/application.properties
- close #127 
먼저 토스페이먼츠 API가 어떤 식으로 작동하는지를 설명드릴께요!
클라이언트에서 최종 결제 승인을 위해 **백엔드 서버에 결제 승인**을 하게 됩니다. 결제 승인 요청을 받은 백엔드 서버는 요청에 담긴 `paymentKey`와 `orderId`를 데이터베이스에 저장을 하고, **토스페이먼츠에 최종 결제 확인을 요청**합니다.
최종 결제가 될 경우, 클라이언트에게 완료 여부를 남깁니다.
오류가 발생할 경우, 토스페이먼츠 서버에서 반환하는 오류 코드를 통해 핸들링이 가능해요.
백엔드 서버에선 토스페이먼츠에서 전달받은 메시지는 **별도의 가공없이 Raw로 클라이언트에 전송**하도록 구현했습니다.
가이드 라인에서 값의 변조를 막기 위해 `Client에서 결제 과정에서 검증을 하는 코드`를 작성하는 것을 권장하고 있어요. 따라서, 아래의 과정과 같이 Session을 통한 검증을 진행할 수 있도록 구현했습니다.
- `TossPayment` : 결제 승인 시, 클라이언트로부터 요청받은 PaymentKey, OrderId와 같은 정보를 저장하는 엔티티
-  JSON (역)직렬화를 위한 jackson 라이브러리 의존성 추가
`Orders`와 `TossPayment`는 일대일 관계를 가집니다. OneToOne으로 관계를 맺어 구현하려고 했으나 **토스 결제 과정에서 Orders에 대한 정보를 어떻게 가져올지** 많이 고민했습니다. `Session`을 통해 가져오는 방법을 생각해냈지만, 구현 과정이 막막하더군요..
주문 조회 시, 결제 정보 또한 조회되도록 구현하기 위해선 필요하다고 생각이 들긴하는데, …
=> feat(toss): 결제승인 API

server/src/main/java/com/onetool/server/api/cart/Cart.java, server/src/main/java/com/onetool/server/api/cart/CartBlueprint.java, server/src/main/java/com/onetool/server/api/cart/repository/CartRepository.java, server/src/main/java/com/onetool/server/api/cart/service/CartServiceImpl.java
- close #134 
- Cart와 CartBlueprint 각각에 대한 save()를 Cart에 대한 save()만 수행하도록 수정
- Transactional을 통한 조회 동기화 문제 해결
CartBlueprint 내의 addBlueprintToCart()는 다음과 같다.
```java
public String addBlueprintToCart(MemberAuthContext user, Long blueprintId){
Member member = findMemberWithCart(user.getId());
Cart cart = member.getCart();
Blueprint blueprint = findBlueprint(blueprintId);
isBlueprintAlreadyInCart(cart, blueprint);
CartBlueprint newCartBlueprint = CartBlueprint.addBlueprintToCart(cart, blueprint);
cartBlueprintRepository.save(CartBlueprint.addBlueprintToCart(cart, blueprint));
updateCartAndSave(cart, newCartBlueprint, Action.ADD);
return "장바구니에 추가됐습니다.";
}
```
위 코드에서 
```java
cartBlueprintRepository.save(CartBlueprint.addBlueprintToCart(cart, blueprint));
``` 
를 통해 CartBlueprint 엔티티에 저장이 한 …
=> fix: 장바구니 읽기, 쓰기, 삭제 버그 수정

server/src/main/java/com/onetool/server/api/member/domain/Member.java, server/src/main/java/com/onetool/server/api/order/OrderBlueprint.java, server/src/main/java/com/onetool/server/api/order/Orders.java, server/src/main/java/com/onetool/server/api/order/controller/OrderController.java, server/src/main/java/com/onetool/server/api/order/dto/request/OrderRequest.java, server/src/main/java/com/onetool/server/api/order/dto/response/OrderResponse.java, server/src/main/java/com/onetool/server/api/order/repository/OrderRepository.java, server/src/main/java/com/onetool/server/api/order/service/OrderServiceImpl.java, server/src/main/java/com/onetool/server/api/payments/TossPayments.java, server/src/main/java/com/onetool/server/api/payments/controller/DepositController.java, server/src/main/java/com/onetool/server/api/payments/controller/TossPaymentController.java, server/src/main/java/com/onetool/server/api/payments/domain/Payment.java, server/src/main/java/com/onetool/server/api/payments/domain/PaymentBlueprint.java, server/src/main/java/com/onetool/server/api/payments/domain/PaymentStatus.java, server/src/main/java/com/onetool/server/api/payments/dto/DepositRequest.java, server/src/main/java/com/onetool/server/api/payments/dto/DepositResponse.java, server/src/main/java/com/onetool/server/api/payments/repository/DepositRepository.java, server/src/main/java/com/onetool/server/api/payments/repository/TossPaymentRepository.java, server/src/main/java/com/onetool/server/api/payments/service/DepositService.java, server/src/main/java/com/onetool/server/api/payments/service/TossPaymentService.java, server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java, server/src/test/java/com/onetool/server/api/order/service/OrderServiceImplTest.java, server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
- close #157 
기존에 작성된 주문과 결제 엔티티를 싹 다 바꾸느라 시간이 결렸습니다..
새롭게 작성한 엔티티는 아래와 같습니다.
현재 `Payment`에서 Status를 관리하고 있습니다. 만약 Payment에서 이를 관리할 경우, **주문 내역 조회 시 주문에 대한 결제를 모두 조회해야하는 상황이 발생**합니다. 고작 상태 칼럼 하나만 조회하기엔 Select 두 번이 매우 비효율적이라고 판단했습니다.
만약 `Orders`에서 status를 관리하면 어떻게 될까요? 이 또한 마찬가지로 결제 확인 후, **status를 update하려면 Payment와 Orders를 Join해야 합니다.**
**저는 Orders에서 관리되는 것이 더 좋다고 생각합니다.** 왜냐하면 Payment에서 관리될 경우 마이페이지 조회 시마다 두 번의 Select가 발생하기 때문입니다. 그러나 update의 경우, 보통 한 번만 이루어지기 때문에 훨씬 효율적이라고 생각되네요!
다른 분들의 생각은 어떨지 궁금합니다.
=> feat(order): 주문, 결제 생성 및 조회

server/src/main/java/com/onetool/server/api/order/controller/OrderController.java, server/src/main/java/com/onetool/server/api/order/service/OrderServiceImpl.java, server/src/main/java/com/onetool/server/api/payments/dto/DepositRequest.java, server/src/main/java/com/onetool/server/api/payments/service/DepositService.java
- close #157 
주문과 결제 정보를 모두 담아서 사용하기에 필드가 너무 많아지고, 복잡해지는 문제가 발생했습니다.
이를 해결하기 위해 주문과 결제에 대한 API를 따로 만들었으나, 결제와 주문의 연관관계를 맺는데 어려움이 있습니다.
주문 생성과 결제 생성이 개별적인 API이기 때문에, 결제 생성 시 주문의 FK를 설정하기 위해 생성한 주문 ID가 필요합니다.
결제하기(주문하기) 버튼 클릭
주문 생성 API 호출
주문 생성 API의 응답으로 주문 ID 반환
결제 생성 API 호출 (body에 주문 ID 첨부)
=> fix(payment): 결제 생성 시 orderId를 Request로 받도록 수정

server/src/main/java/com/onetool/server/api/order/controller/OrderController.java, server/src/main/java/com/onetool/server/api/order/dto/request/OrderRequest.java, server/src/main/java/com/onetool/server/api/payments/dto/DepositResponse.java, server/src/main/java/com/onetool/server/api/payments/service/DepositService.java, server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java
- close #160 
- 주문하려는 도면이 없는 경우 예외 발생
- Set 컬렉션을 통한 주문하려는 도면 중복되는 문제 해결
- Payment의 orderId가 존재하지 않는 주문일 경우 예외 발생
- 결제 생성 시, blueprintId를 입력받지 않도록 수정
@Valid를 사용하여 DTO의 유효성 검사를 하도록 구현했습니다.
결제 상태에 대해 추가적인 수정이 필요해보여요.
=> fix(payment, order): 예외 처리

server/src/main/java/com/onetool/server/api/member/controller/MemberController.java, server/src/main/java/com/onetool/server/api/member/service/MemberService.java, server/src/main/java/com/onetool/server/api/order/OrderBlueprint.java, server/src/main/java/com/onetool/server/api/order/Orders.java, server/src/main/java/com/onetool/server/api/order/dto/response/OrderResponse.java, server/src/main/java/com/onetool/server/api/order/service/OrderServiceImpl.java, server/src/main/java/com/onetool/server/api/payments/domain/Payment.java, server/src/main/java/com/onetool/server/api/payments/domain/PaymentStatus.java
- close #166 
- 기존 결제 엔티티에 있던 결제 상태를 주문 엔티티로 이동
- 결제 상태에 결제 취소 추가
- 결제 상태가 `결제완료`인 주문에 대해서만 제대로된 다운로드 링크 반환
=>  feat(order): 주문 상태 및 다운로드 URL 활성화 구현

server/src/main/java/com/onetool/server/api/member/domain/Member.java, server/src/main/java/com/onetool/server/api/member/dto/MemberUpdateRequest.java, server/src/main/java/com/onetool/server/api/member/service/MemberService.java
- close #164 
- 비밀번호 변경 로직을 추가
- setter을 통한 유저 정보 업데이트
기존 코드는 Equal을 통해 이름과 비밀번호을 변경할 경우, 비밀번호만 변경되지 않는 문제가 발생했어요.
```java
@Transactional
public void updateWith(MemberUpdateRequest request, PasswordEncoder encoder) {
Optional.ofNullable(request.getName()).ifPresent(this.name = name);
Optional.ofNullable(request.getNewPassword()).ifPresent(newPassword -> {
log.info("new password: {}", newPassword);
this.password = encoder.encode(newPassword);
});
```
비밀번호만 변경하는 경우에는 update 쿼리가 아예 실행되지 않은 것을 발견했습니다. 
이를 통해 긴 문자열 (인코딩된 비밀번호)는 equal을 통해 더티체킹이 발생하지 않는다는 것을 발견했다.
따라서, 이를 해결하기 위해 Hibernate가 더티체킹 가능하도록 `setter`을 통해 값을 변경하여 이를 해결했다.
=> feat(member): 비밀번호 변경되지 않던 문제 해결

server/src/main/java/com/onetool/server/api/blueprint/Blueprint.java, server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java, server/src/main/java/com/onetool/server/data/DataLoader.java, server/src/main/java/com/onetool/server/data/DummyDataLoader.java, server/src/main/java/com/onetool/server/data/TestDataLoader.java
- #178 
- Blueprint에 카테고리 검색 인덱스 추가
- Blueprint와 FirstCategory를 Join하는 대신 Blueprint에서 Join 키를 통해 조회하도록 수정
- 도면 더미테이스 수 1,000,000으로 증가
- chore: DataLoader를 data 패키지로 이동
> [!IMPORTANT]
> 데이터 1,000,000건을 기준으로 테스트 됐습니다. 
기존 2차 카테고리 검색 쿼리의 경우, FirstCategory를 `서브쿼리로`하여 검색한다. 일반적으로 서브쿼리보다 **Join이 비용이 더 적다**고 알고 있어 쿼리를 수정해보았다.
```sql
@Query(value = """
SELECT b FROM Blueprint b WHERE b.secondCategory = :second
AND b.categoryId = (SELECT f.id FROM FirstCategory f WHERE f.name = :first)
AND b.inspectionStatus = :status
""")
Page<Blueprint> findAllBySecondCategory(@Param("first") String firstCategory, @Param("second") String secondCategory, @Param("status") InspectionStatus status, Pageable pageable);
```
```sql
@Query(value = """
SELECT b FROM Blueprint b JOIN FETCH FirstCategory f
ON b.categoryId …
```
=> refactor(blueprint): 커버링 인덱스를 통한 카테고리 검색 성능 개선

server/src/main/java/com/onetool/server/global/new_exception/exception/BaseException.java, server/src/main/java/com/onetool/server/global/new_exception/exception/error/ErrorCode.java, server/src/main/java/com/onetool/server/global/new_exception/exception/error/ErrorDisplayType.java, server/src/main/java/com/onetool/server/global/new_exception/exception/handler/GlobalExceptionHandler.java, server/src/main/java/com/onetool/server/global/new_exception/exception/response/ErrorResponse.java
- #177 
새로운 예외 처리 로직을 구현했습니다.
이미 작성한 예외 처리 로직을 수정한 것이 아닌 새로 디렉토리를 만들어서 구현한 것입니다.
```
{
errorCode : "MEMBER-0000",
message : "회원이 존재하지 않습니다.",
displayType : "MODAL"
}
```
- displayType => Popup, Toast, Modal : 유저에게 에러를 어떻게 보여줄 것인가?
- 실선 : 멤버 변수로 가지고 있고, 사용하는 경우
- 점선 : 지역변수로 사용하거나, 파라미터로 사용하는 등 멤버변수로 갖지 않고 사용하는 관계
<aside>
💡 개발자가 직접 예외를 선언하는 경우에 따른 시퀀스
</aside>
> 모든 `Exception`을 `BaseException`으로 처리
> 
1. `ErrorCode`를 명시하여 `BaseException` 을 발생
2. `BaseException`이 발생하면 `GlobalExceptionHandler`의 `BaseException` 핸들러가 동작
3. `GlobalExceptionHandler`는 `BaseException`에 커스텀 메세지 존재여부 확인
- 커스텀 메세지 존재 시 정의된 `ErrorCode`의 메세지에 커스텀 메세지를 넣어 인스턴스 생성<1.1.2>
- 커스텀 메세지 미존재 시 정의된 `ErrorCode`를 통해 인스턴스 생성<1.1.3>
4. HTTP 응답 메세지 Body에 `ErrorResponse` 인스턴스를 전달
+) 추가로 Binding관련 Exception은 따로 Handler를 만들어야 합니다
애초에 …
=> [refactor] 예외 처리 로직 변경

server/src/main/java/com/onetool/server/api/member/business/MemberEmailBusiness.java, server/src/main/java/com/onetool/server/api/member/business/MemberLoginBusiness.java, server/src/main/java/com/onetool/server/api/member/controller/MemberEmailController.java, server/src/main/java/com/onetool/server/api/member/controller/MemberLoginController.java, server/src/main/java/com/onetool/server/api/member/service/MemberService.java, server/src/main/java/com/onetool/server/global/new_exception/exception/error/LoginErrorCode.java, server/src/main/java/com/onetool/server/global/new_exception/exception/error/MemberErrorCode.java
- #177 
- 커스텀 예외나 BaseException 대신 `ApiException`을 사용하도록 변경
- MemberErrorCode와 LoginErrorCode 정리
예를 들어 id가 5인 Member를 찾는 서비스 로직 실행 중 `NON_EXIST_MEMBER`가 발생했다고 해보죠. 이때, **5 라는 값을 커스텀 메시지로 넘기는 것**에 대해 어떻게 생각하시나요?
아래와 같은 코드로 변경하는 것이 의미가 있을지 의견이 궁금합니다!
```java
@Transactional(readOnly = true)
public Member findById(Long id) {
return memberRepository.findById(id).orElseThrow(() ->
new ApiException(MemberErrorCode.NON_EXIST_USER, "ID가 일치하는 회원이 존재하지 않습니다. :" + id));
}
```
진짜 뜬금없지만, `+`와 `StringBuilder`의 속도 차이에 대한 글도 남겨봐요!
[Compact String 과 String plus연산은 왜느릴까?](https://nelmm.gitbook.io/nelmm/6./compact-string-string-plus)
=> refactor(member): 회원 예외 구조 변경

server/build.gradle, server/src/main/java/com/onetool/server/global/config/SecurityConfig.java, server/src/main/java/com/onetool/server/global/config/SwaggerConfig.java
- close #이슈번호
Swagger-ui 기능을 도입했습니다
토큰을 넣는 방식은 해당 사진에서 Authorize를 클릭 후 발급받은 토큰을 넣으시면 되겠습니다.
refreshToken을 찾으시려면 F12개발자 도구에서 쿠키에서 꺼내시면 됩니다!!
Swagger에는 개발자들이 사용하기 쉽게 정리할 수 있는 기능들이 있다고 합니다!! 
아직은 그 기능들을 도입하지 않았고 태초의 상태?? 형태로 적용했습니다.
=> feat(swagger-ui) :  swagger-ui 기능 구현

server/src/main/java/com/onetool/server/api/cart/Cart.java, server/src/main/java/com/onetool/server/api/member/repository/MemberRepository.java, server/src/main/java/com/onetool/server/global/auth/filter/JwtAuthFilter.java, server/src/main/java/com/onetool/server/global/auth/login/service/CustomUserDetailsService.java
[N+1을 통한 성능 리팩터링](#178) 
- close #이슈번호
다만 filter를 거치게 되면 아래와 같이 Member 와 cart가 둘다 각각 조회되는 N+1문제가 발생한다. 
여기서 추가적으로 Member과 한번 더 새롭게 조회되는 문제가 발생했다.
즉 정리하자면 Member cart 조회 그리고 다시 Member cart 조회 .. 이는 매우 비효율적이다.
```
2025-03-05T17:47:50.949+09:00  INFO 15496 --- [server] [nio-8080-exec-1] c.o.s.global.auth.filter.JwtAuthFilter   : 토큰: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiZW1haWwiOiJra2QwNjE0NEBuYXZlci5jb20iLCJtZW1iZXJJZCI6MywiaWF0IjoxNzQxMTU0NjcwLCJleHAiOjI5NTA3NTQ3MDN9.26FIzgFueAFHClrmXuwb3kL4_LL2tBNhG_t4hiaQ6p8
2025-03-05T17:47:50.950+09:00  INFO 15496 --- [server] [nio-8080-exec-1] c.o.server.global.auth.jwt.JwtUtil       : parseClaims token: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiZW1haWwiOiJra2QwNjE0NEBuYXZlci5jb20iLCJtZW1iZXJJZCI6MywiaWF0IjoxNzQxMTU0NjcwLCJleHAiOjI5NT …
```
=> refactor(filter): 필터 검사시 Member 쿼리자체가 2번 조회되는 문제와 N+1 문제가 발생 해결

server/src/main/java/com/onetool/server/api/blueprint/business/BlueprintSearchBusiness.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java, server/src/main/java/com/onetool/server/api/cart/business/CartBusiness.java, server/src/main/java/com/onetool/server/api/member/business/MemberBusiness.java, server/src/main/java/com/onetool/server/api/member/business/MemberEmailBusiness.java, server/src/main/java/com/onetool/server/api/member/business/MemberLoginBusiness.java, server/src/main/java/com/onetool/server/api/member/repository/MemberRepository.java, server/src/main/java/com/onetool/server/api/member/service/MemberService.java, server/src/main/java/com/onetool/server/api/order/business/OrderBusiness.java, server/src/main/java/com/onetool/server/api/qna/business/QnaBoardBusiness.java, server/src/main/java/com/onetool/server/api/qna/business/QnaReplyBusiness.java, server/src/main/java/com/onetool/server/data/TestDataLoader.java, server/src/test/java/com/onetool/server/api/member/business/MemberBusinessTest.java, server/src/test/java/com/onetool/server/api/member/fake/FakeMemberRepository.java, server/src/test/java/com/onetool/server/api/payments/service/DepositServiceTest.java, server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java, server/src/test/java/com/onetool/server/category/CategoryServiceTest.java
- close #이슈번호
- TestDataLoader에서 회원 생성 코드를 `MemberBusinessTest`의 `@Beforeeach`으로 이동
- FakeMemberRepository 생성
- MemberRepository가 Repository를 implement하도록 수정하여 가짜 객체를 모듈화
테스트 방법에 대해 3가지 체크 리스트를 두고 선정했으면 합니다.
다음과 같이 체크 리스트를 만든 이유는 이렇습니다. CI 단계에서 모든 테스트 코드를 통과한 실제 배포 환경에 반영하고자 합니다. 그렇기 위해선 **테스트 코드 속도가 극단적으로 느리면 CI 시간이 길어지게되는 단점**이 존재합니다.
**테스트 코드는 서비스 로직을 이해할 수 있는 코드**라고 생각합니다. 그렇기 위해선 코드의 가독성이 어느정도 필요하다고 생각이 듭니다. 빈을 주입하거나 필요한 소스를 생성하는 코드를 다른 클래스로 빼서 사용하는 방법도 이에 포함될 것 같습니다.
<br/>
회원을 생성하는 코드를 3가지 방법으로 테스트 해보았다.
**[ Mockito ]**
```java
@Test
void create_member() {
// given
final Map<String, Object> params = Map.of(
"email", "user@example.com",
"password", "1234",
"name", "일반유저",
"birthDate", "2001-03-28",
"development_field", "백엔드",
"phoneNum", "01000000000",
"isNative", true
);
// when …
```
=> test(member): Fake Repository 기반 테스트 코드

server/build.gradle, server/src/main/java/com/onetool/server/api/member/dto/BlueprintDownloadResponse.java, server/src/main/java/com/onetool/server/api/qna/repository/QnaBoardRepository.java, server/src/main/resources/application-local.properties, server/src/test/java/com/onetool/server/api/helper/MockBeanInjection.java, server/src/test/java/com/onetool/server/api/member/business/MemberBusinessTest.java, server/src/test/java/com/onetool/server/api/member/controller/MemberControllerTest.java, server/src/test/java/com/onetool/server/api/member/fake/FakeMemberRepository.java, server/src/test/java/com/onetool/server/api/member/fixture/MemberFixture.java, server/src/test/java/com/onetool/server/api/member/fixture/WithMockPrincipalDetails.java, server/src/test/java/com/onetool/server/api/member/fixture/WithMockPrincipalDetailsSecurityContextFactory.java, server/src/test/java/com/onetool/server/api/member/service/MemberServiceTest.java
- #210
- MemberFixture 생성
- 테스트 더블을 이용한 Service 테스트 코드 작성
- Mockito를 이용한 Business 테스트 코드 작성
- Mockito를 이용한 Controller 테스트 코드 작성
- Spring Security를 위한 CustomMockUser 생성
현재 MemberFixture에는 Stubbing을 위해 DTO를 생성하는 메서드를 만들었습니다.
**MemberFixture**
```java
public static MemberCreateResponse createMemberCreateResponse() {
return MemberCreateResponse.builder()
.id(2L)
.name("홍길동")
.email("user@example.com")
.build();
}
```
```java
@Test
@WithMockUser(username = "test@gmail.com", password = "0000")
void 회원을_생성한다() throws Exception {
// given
MemberCreateRequest request = MemberFixture.createMemberCreateRequest();
MemberCreateResponse response = MemberFixture.createMemberCreateResponse();
when(memberBusiness.createMember(request)).thenReturn(response); // ✅ 여기서 사용
// when
ResultActions resultActions …
```
=> test(member): Mockito를 이용한 controller - business - service 테스트 작성

server/build.gradle, server/src/main/java/com/onetool/server/api/blueprint/Blueprint.java, server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java, server/src/main/java/com/onetool/server/api/order/Orders.java, server/src/main/java/com/onetool/server/api/order/business/OrderBusiness.java, server/src/main/java/com/onetool/server/api/order/controller/OrderController.java, server/src/main/java/com/onetool/server/api/order/dto/response/MyPageOrderResponse.java, server/src/main/java/com/onetool/server/api/order/repository/OrderRepository.java, server/src/main/java/com/onetool/server/api/order/service/OrderService.java, server/src/main/java/com/onetool/server/global/entity/BaseEntity.java, server/src/main/java/com/onetool/server/global/redis/config/RedisCacheConfig.java
- close #이슈번호
해당 코드는 LAZY로 지연로딩만 설정되어 있고 fetch join 등등 아무것도 안한 상태에서 측정한 결과이다.
그렇다면 쿼리 수가 어떻게 2011이 나왔는지 분석해보자 .
일단 실험을 위해 orders 테이블과 그의 자식 OneToMany로 되어있는 orderBlueprintList 가 있다. 
처음 데이터베이스에 orders에 1000개의 데이터를 삽입하였고 orderBlueprintList 각각 orders하나당 200개씩 데이터를 넣어 
총 20만개의 데이터를 넣었따. 
즉 orders 1L 당 orderBlueprint는 200개씩 있는 셈이다.
처음 1은 member 쿼리를 날릴 때 사용된 쿼리.
두번째 1은 1000개의 orders를 조회하기 위한 쿼리.
즉 order 객체 하나당 payMent 객체가 1:1로 설정되어 있는데 조회 될 때마다 payMent가 실제로 데이터베이스에 있는지 아닌지Hibernate가 쿼리를 직접 날려본다. 그래서 1000개의 orders가 있다면 1000개의 payMent 쿼리를 날리게 된다.
네번째 9는 blueprint 객체 수이다. 
현재 데이터베이스는 9개의 blueprint가 저장되어 있는데 orders의 데이터에 blueprint가 랜덤값으로 저장되게 해놨다. 
그래서 blueprint를 찾을 때마다 쿼리 한개씩 보내게 되는 것이다.
orderItems 가 OneToMany Lazy로 설정되어 있기 때문에 매번 해당 객체에 접근할 때마다 쿼리를 보내게 된다.
---
쿼리를 분석해보자 
1(멤버 쿼리) + 1(order 조회시 모든 …
=> feat(Orders): orders N+1문제 해결 2010 쿼리 -> 13개 쿼리 => 캐시 적용

server/src/main/java/com/onetool/server/api/blueprint/Blueprint.java, server/src/main/java/com/onetool/server/api/cart/Cart.java, server/src/main/java/com/onetool/server/api/cart/CartBlueprint.java, server/src/main/java/com/onetool/server/api/cart/business/CartBusiness.java, server/src/main/java/com/onetool/server/api/cart/controller/CartController.java, server/src/main/java/com/onetool/server/api/cart/dto/request/AddBlueprintToCartRequest.java, server/src/main/java/com/onetool/server/api/cart/dto/response/CartItemResponse.java, server/src/main/java/com/onetool/server/api/cart/dto/response/CartItemsResponse.java, server/src/main/java/com/onetool/server/api/cart/service/CartService.java, server/src/test/java/com/onetool/server/api/cart/business/CartBusinessTest.java, server/src/test/java/com/onetool/server/api/cart/controller/CartControllerTest.java, server/src/test/java/com/onetool/server/api/cart/fixture/CartFixture.java, server/src/test/java/com/onetool/server/api/cart/service/CartServiceTest.java, server/src/test/resources/application-test.yml, server/src/test/resources/application.yml
- #212 
테스트용 데이터베이스 설정파일을 추가했습니다.
각 테스트 클래스마다 
`@ActiveProfiles("test")
`
를 정의해주시면 모든 테스트는 테스트 디렉토리 안에 있는 application-test.yml 설정이 활성화 됩니다. 
```
@ExtendWith(MockitoExtension.class)
@ActiveProfiles("test")
@SuppressWarnings("NonAsciiCharacters")
public class CartServiceTest {
@Mock
private CartRepository cartRepository;
@Mock
private CartBlueprintRepository cartBlueprintRepository;
@InjectMocks
private CartService cartService;
```
- @ActiveProfiles("test")가 적용되어 테스트 환경 설정(application-test.yml)을 로드
- Mock으로 생성된 cartRepository, cartBlueprintRepository를 CartService에 자동으로 주입
- @Mock을 활용해 실제 데이터베이스에 접근하지 않고, 테스트에서 원하는 동작을 시뮬레이션 가능
Cart - CartBlueprint - Blueprint가 연관관계에 있는 상태이므로
테스트 환경에서는 엔티티 간의 연관관계를 유지하면서도 독립적이고 재사용 가능한 Fixture를 생성
즉, Cart를 생성할 때 CartBlueprint와 Blueprint도 함께 생성되도록 설계
- 엔드포인트 …
=> test(Cart) Cart 테스트 코드 작성

server/src/main/java/com/onetool/server/api/member/business/MemberBusiness.java, server/src/main/java/com/onetool/server/api/member/domain/Member.java, server/src/main/java/com/onetool/server/api/member/repository/MemberJpaRepository.java, server/src/main/java/com/onetool/server/api/member/repository/MemberRepository.java, server/src/main/java/com/onetool/server/api/member/service/MemberService.java, server/src/test/java/com/onetool/server/api/member/fake/FakeMemberJpaRepository.java, server/src/test/java/com/onetool/server/api/member/service/MemberServiceTest.java
- close #이슈번호
현재 DB Member table 에는 100만개의 데이터가 저장되어 있다. 
```
@Query("SELECT m FROM Member m WHERE m.name = :name AND m.phoneNum = :phoneNum")
Optional<Member> findByNameAndPhoneNum(@Param("name") String name, @Param("phoneNum") String phoneNum);
```
해당 쿼리에 관련해서 성능 최적화를 해보았습니다.
위의 JPQL 코드는 데이터베이스에서 아래와 같은 형태의 쿼리로 바뀐다
```
SELECT * FROM member m
WHERE m.name = 'User00021'
AND m.phone_num = '01036939764'
AND m.is_deleted = false;
```
Member 에는 email과 pk_id 만 인덱스로 설정되어 있어서 name과 phoneNum는 idx가 설정되어 있지 않습니다.
그래서 만약 Member 레코드가 100만개라고 한다면 name 은  index가 없어서 풀테이블 스캔이 일어나 
100만개의 모든 레코드를 조회해야 되는 최악 상황이 발생합니다.
이러한 이유로 다음아래의 과정을 통해 성능 최적화를 진행했습니다.
- `name` 혹은 `phone_num` 중 하나만 인덱스를 설정한 경우:
- 옵티마이저는 해당 **인덱스 트리**를 통해 **리프 노드의 `pk_id` 주소**를 탐색한다.
- 이후 `pk`가 만든 **클러스터링 인덱스**를 통해 최종적으로 원하는 **레코드**를 …
=> feat(Member): idx_name 적용 2.67TPS => 771TPS 성능향상

server/src/main/java/com/onetool/server/ServerApplication.java, server/src/main/java/com/onetool/server/api/chat/domain/ChatMessage.java, server/src/main/java/com/onetool/server/api/chat/domain/ChatMessageQueue.java, server/src/main/java/com/onetool/server/api/chat/handler/ChatWebSocketHandler.java, server/src/main/java/com/onetool/server/api/chat/handler/TestChatWebSocketHandler.java, server/src/main/java/com/onetool/server/api/chat/repository/ChatMysqlSpringImpl.java, server/src/main/java/com/onetool/server/api/chat/repository/ChatPostgresRepositoryImpl.java, server/src/main/java/com/onetool/server/api/chat/repository/ChatRepository.java, server/src/main/java/com/onetool/server/api/chat/service/ChatProcessService.java, server/src/main/java/com/onetool/server/api/chat/service/ChatService.java, server/src/main/resources/application-local.properties, server/src/main/resources/application.properties, server/src/test/java/com/onetool/server/api/chat/service/ChatMessageQueueTest.java
- close #230 
원툴의 채팅을 도입하여 도면에 대한 이야기를 하거나 정보를 공유할 수 있는 커뮤니케이션 도구를 개발하려고 한다. 사용성 측면에서 보다 구현이 용이한 공개채팅으로 구현하고자 한다.
모놀리식 아키텍처를 통해 서버 비용을 절감하기 위해 별도의 프레임워크가 아닌 기존에 사용중인 Java와 Spring Boot를 사용하기로 결정했다.
1:1이 아닌 다수의 사용자가 동시에 진행할 수 있는 채팅을 구현하기 위해 어떤 메시지 전송 방식이 접합할지 장단점을 구분했다.
| 방식 | 장점 | 단점 |
| --- | --- | --- |
| **HTTP Polling** | 서비스 구현이 간편 | - Polling 주기에 따라 메시지 전송 속도가 결정 <br/> - Polling된 시점에 따라 사용자가 보고 있는 채팅 내용이 결정됨 |
| **WebSocket** | - 모든 시점에서 사용자의 채팅 내용이 일치 <br/> - 여러 사용자에게 동시에 브로드캐스트 가능 | - 연결이 많아지면 복잡한 세션 관리 <br/> - Stateful 방식으로 연결 관리 필요 |
| **gRPC** | - 멀티플렉싱을 통한 동시 요청 처리 <br/> - Protocol Buffers로 타입 안정성 <br/> - 스트리밍 지원 <br/> - 부하분산 내장 | - 브라우저 지원 제한 <br/> - 러닝 커브 존재 <br/> - 브로드캐스팅 부재 (각각 유니캐스트) |
공개 채팅 특성상 브로드캐스트가 간편한 **WebSocket**을 채택했다. 
현재 사용 중인 MySQL을 그대로 사용하기로 결정했다. 추후 성능 테스트를 …
=> feat(chat): 채팅 시스템 및 MessageQueue 도입
