.idea/.gitignore
.idea/backend.iml
.idea/compiler.xml
.idea/gradle.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/uiDesigner.xml
.idea/vcs.xml
server/src/main/java/com/onetool/server/blueprint/Blueprint.java
server/src/main/java/com/onetool/server/category/FirstCategory.java
server/src/main/java/com/onetool/server/category/SecondCategory.java

feat: category, blueprint Entity 추가했습니다. 
문제시 바로 알려주세요!

feat: category, blueprint Entity 추가

---

server/src/main/java/com/onetool/server/blueprint/Blueprint.java
server/src/main/java/com/onetool/server/cart/Cart.java
server/src/main/java/com/onetool/server/cart/CartBlueprint.java
server/src/main/java/com/onetool/server/order/OrderBlueprint.java
server/src/main/java/com/onetool/server/order/Orders.java
server/src/main/java/com/onetool/server/payments/Payments.java

Orders : Order에서 Orders로 명칭 수정
CartItems, OrderItems -> OrderBlueprint, CartBlueprint로 명칭 수정 Orders(Cart)와 Blueprint의 다대다 관계 -> OrderBlueprint(CartBlueprint) 중간 테이블로 풀어냄 Payments : Orders관한 매핑 변수명 수정

[feat] 엔티티 관련 수정

---

.idea/gradle.xml
server/src/main/java/com/onetool/server/blueprint/Blueprint.java
server/src/main/java/com/onetool/server/blueprint/BlueprintController.java
server/src/main/java/com/onetool/server/blueprint/BlueprintRepository.java
server/src/main/java/com/onetool/server/blueprint/BlueprintRequest.java
server/src/main/java/com/onetool/server/blueprint/BlueprintResponse.java
server/src/main/java/com/onetool/server/blueprint/BlueprintService.java

- 도면 상세 조회 기능 추가 
- Buleprint Entit에서 creatorName 누락 추가

Feat:  도면 상세 조회 기능 추가

---

.gitmodules
.idea/.gitignore
server/src/main/java/com/onetool/server/blueprint/BlueprintRepository.java
server/src/main/java/com/onetool/server/blueprint/BlueprintService.java
server/src/main/java/com/onetool/server/blueprint/SearchController.java
server/src/main/resources/data.sql

- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [레포 이름 #이슈번호](이슈 주소)
<br/>

feat: 서브모듈 추가

---

.idea/compiler.xml
server/src/main/java/com/onetool/server/blueprint/BlueprintRepository.java
server/src/main/java/com/onetool/server/counting/MainPageController.java
server/src/main/java/com/onetool/server/counting/ServiceCountingService.java
server/src/main/java/com/onetool/server/counting/dto/ServiceCountingResponse.java
server/src/main/java/com/onetool/server/member/MemberRepository.java

- 메인페이지의 서비스 현황 추가
<br/>
- 판매 수는 현재 Order 개발의 미흡으로 추후 수정
<br/>
<br/>

feat: 서비스 현황 API

---

server/src/main/java/com/onetool/server/global/exception/BaseException.java
server/src/main/java/com/onetool/server/global/exception/BaseResponse.java
server/src/main/java/com/onetool/server/global/exception/WebErrorController.java
server/src/main/java/com/onetool/server/global/exception/codes/BaseCode.java
server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java
server/src/main/java/com/onetool/server/global/exception/codes/SuccessCode.java
server/src/main/java/com/onetool/server/global/exception/howToUse/TempController.java
server/src/main/java/com/onetool/server/global/exception/howToUse/service/TempService.java
server/src/main/java/com/onetool/server/global/exception/howToUse/service/TempServiceImpl.java
server/src/main/java/com/onetool/server/global/exception/howToUse/temp/TempConverter.java
server/src/main/java/com/onetool/server/global/exception/howToUse/temp/TempRequest.java
server/src/main/java/com/onetool/server/global/exception/howToUse/temp/TempResponse.java
server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
server/src/main/java/com/onetool/server/global/handler/MyExceptionHandler.java

exception 관련 클래스 패키지 경로가 잘못돼 수정했습니다.

chore : exception 관련 클래스 패키지 경로 수정

---

server/src/main/java/com/onetool/server/global/exception/BaseException.java
server/src/main/java/com/onetool/server/global/exception/codes/BaseCode.java
server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java
server/src/main/java/com/onetool/server/global/exception/codes/SuccessCode.java
server/src/main/java/com/onetool/server/global/exception/codes/reason/Reason.java
server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
server/src/main/java/com/onetool/server/qna/QnaBoard.java
server/src/main/java/com/onetool/server/qna/QnaReply.java
server/src/main/java/com/onetool/server/qna/controller/QnaController.java
server/src/main/java/com/onetool/server/qna/controller/QnaReplyController.java
server/src/main/java/com/onetool/server/qna/dto/request/QnaRequest.java
server/src/main/java/com/onetool/server/qna/dto/response/QnaResponse.java
server/src/main/java/com/onetool/server/qna/repository/QnaRepository.java
server/src/main/java/com/onetool/server/qna/service/QnaService.java
server/src/main/java/com/onetool/server/qna/service/QnaServiceImpl.java

[refactor] Reason 관련 클래스 경로 수정
[feat] 문의사항 관련 기능 추가
[chore] QnaBoard, QnaReply 엔티티 수정 및 매핑 메서드, 정적 팩토리 메서드 추가

[refactor, feat, chore] : 리팩토링 및 문의사항 기능 추가

---

server/src/main/java/com/onetool/server/member/domain/Member.java
server/src/main/java/com/onetool/server/member/service/MemberService.java

- 0~10까지의 수로 랜덤하게 생성된 15자리의 임시비밀번호를 메일로 발송합니다.
<br/>
- 비밀번호 찾기
<br/>
<br/>

feat: 비밀번호 찾기 시, 임시 비밀번호 생성 및 발급

---

server/src/main/java/com/onetool/server/blueprint/dto/BlueprintResponse.java
server/src/main/java/com/onetool/server/cart/controller/CartController.java
server/src/main/java/com/onetool/server/cart/dto/CartRequest.java
server/src/main/java/com/onetool/server/cart/service/CartService.java
server/src/main/java/com/onetool/server/cart/service/CartServiceImpl.java

- 장바구니 api 추가 및 수정
<br/>
- 예외 처리 추가
<br/>

[feat] 장바구니 api 추가

---

.idea/.gitignore
server/src/main/java/com/onetool/server/member/service/MemberService.java

- createRandomPassword의 class, interface or enum expected 문제 해결 
<br/>
-
-
<br/>
<br/>

 fix: createRandomPassword class, interface or enum expected 해결

---

dockerfile
server/src/main/java/com/onetool/server/member/service/MemberService.java
server/src/main/resources/application.properties

- dockerfile 수정
<br/>
<br/>
<br/>

fix: dockerfile 수정

---

server/src/main/java/com/onetool/server/cart/Cart.java
server/src/main/java/com/onetool/server/cart/CartBlueprint.java
server/src/main/java/com/onetool/server/cart/repository/CartBlueprintRepository.java
server/src/main/java/com/onetool/server/cart/service/CartService.java
server/src/main/java/com/onetool/server/cart/service/CartServiceImpl.java
server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java
server/src/main/java/com/onetool/server/member/domain/Member.java

feat : 장바구니 기능 수정
- 회원가입 시 장바구니 자동 생성
<br/>
<br/>

feat : 장바구니 기능 수정

---

server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
server/src/main/java/com/onetool/server/global/config/WebConfig.java
server/src/main/java/com/onetool/server/member/controller/MemberController.java
server/src/main/java/com/onetool/server/member/service/MemberService.java

- SecurityConfig에 CorsConfiguration추가 4개의 origin URL 허용
1. http://www.onetool.co.kr
2. http://onetool.co.kr
3. http://localhost:3000
4. https://accounts.google.com
- WebConfig에서 WebMvcConfigurer 구현
<br/>
- 회원 정보 수정 및 조회 API 수정
<br/>
<br/>

feat: CORS 설정 추가

---

server/src/main/java/com/onetool/server/blueprint/Blueprint.java
server/src/main/java/com/onetool/server/blueprint/service/BlueprintService.java
server/src/main/java/com/onetool/server/cart/Cart.java
server/src/main/java/com/onetool/server/cart/service/CartService.java
server/src/main/java/com/onetool/server/cart/service/CartServiceImpl.java
server/src/main/java/com/onetool/server/order/OrderBlueprint.java
server/src/main/java/com/onetool/server/order/controller/OrderController.java
server/src/main/java/com/onetool/server/order/dto/request/OrderItem.java
server/src/main/java/com/onetool/server/order/dto/request/OrderRequest.java
server/src/main/java/com/onetool/server/order/dto/response/OrderResponse.java
server/src/main/java/com/onetool/server/order/repository/OrderDiabetesRepository.java
server/src/main/java/com/onetool/server/order/repository/OrderRepository.java
server/src/main/java/com/onetool/server/order/service/OrderService.java
server/src/main/java/com/onetool/server/order/service/OrderServiceImpl.java

refactor : 장바구니, 주문 서비스 로직 리펙토링

refactor : 장바구니, 주문 서비스 로직 리펙토링

---

server/src/main/resources/application.properties

- ec2 ip주소에서 localhost로 변경
<br/>
<br/>
<br/>

chore: mysql 주소를 ec2 ip에서 변경

---

server/build.gradle

-  build.gradle 에 관련 의존성 추가 
<br/>
<br/>
[likelion-onetool #72 ](https://github.com/likelion-onetool/backend/issues/72 )
<br/>

[#72] test: MockMVC를 사용하여 @AuthenticationPrincipal 전달하기

---

server/build.gradle
server/src/main/java/com/onetool/server/DataLoader.java
server/src/main/java/com/onetool/server/TestDataLoader.java
server/src/main/java/com/onetool/server/global/auth/jwt/JwtUtil.java
server/src/main/java/com/onetool/server/global/exception/ApiResponse.java
server/src/main/java/com/onetool/server/member/dto/MemberUpdateRequest.java
server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
server/src/test/java/com/onetool/server/member/MemberServiceTest.java

- Mock 사용 테스트 코드와 Mcok 미사용 테스트 코드 분리
- `BlueprintServviceBockTest`와 `BlueprintServiceTest`로 분리
- @MockBean을 통한 JwtUtil 빈 주입
- ApiResponse의 기본 생성자 생성
- 토큰 생성 테스트를 위한 테스트 코드 추가
<br/>
- Mock 사용 시, JWT Token이 정상적으로 생성되지 않는 문제 해결
<br/>
#80 
1, 2번 문제 해결
<br/>

test(blueprint): MockBean과 ObjectMapper 오류 해결

---

.github/workflows/dev_deploy.yml
compose.yml
server/build.gradle
server/src/main/java/com/onetool/server/DataLoader.java
server/src/main/java/com/onetool/server/TestDataLoader.java
server/src/main/java/com/onetool/server/global/auth/jwt/JwtUtil.java
server/src/main/java/com/onetool/server/global/exception/ApiResponse.java
server/src/main/java/com/onetool/server/member/dto/MemberUpdateRequest.java
server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
server/src/test/java/com/onetool/server/member/MemberServiceTest.java

- dev 브랜치에 merge될 경우, 파이프라인 작동
- onetool-test-server EC2 컨테이너 사용
- Docker Hub를 통해 이미지 생성 후, EC2 컨테이너에서 이미지로 컨테이너 생성 및 실행
- Docker Compose를 통해 MySQL과 Spring Boot 빌드
- Spring Boot 빌드 시, Profile은 dev로 설정
<br/>
- CI/CD 안정성 확인
- EC2 Redis 설치 및 등록
<br/>
#75 
<br/>

[#75] feat(deploy): CI/CD & compose 파일 생성

---

.github/workflows/dev_deploy.yml

dockerfile의 잘못된 경로 변경
<br/>
<br/>
#75 
<br/>

chore(deploy): docker 이미지 경로 수정

---

server/build.gradle

- ALB의 헬스체크를 위해 추가
- `/actuator/health`을 통해 ALB에서 대상그룹에 대한 health check 수행
<br/>
#75 
<br/>

chore: Actuator 라이브러리 추가

---

server/src/main/java/com/onetool/server/DataLoader.java

dev 프로파일 환경에서 실행되도록 default에서 변경
<br/>
<br/>
#75 
<br/>

fix: DataLoader 프로파일 변경

---

server/src/main/java/com/onetool/server/global/config/SecurityConfig.java

- Spring Security Configuration에서 filterChain에 `preflight 관련 요청`을 `permitAll`하도록 수정했어요.
<br/>
- CORS 문제 발생 확인 및 방안 모색
<br/>
#93 
<br/>

fix(security): PreFlight 요청 허가

---

server/src/main/java/com/onetool/server/DataLoader.java
server/src/main/java/com/onetool/server/api/blueprint/Blueprint.java

검색어를 이용한 도면 검색이 되지 않는 문제를 해결했어요.
도면의 검수 여부가 완료되지 않은 도면은 검색되지 않아요.
따라서 테스트 도면에 대한 검수 여부를 수정했어요.
- Blueprint의 inspectionStatus를 NONE으로 기본설정
- 테스트 도면 중 일부를 NONE으로 설정
<br/>
- 도면 검색 기능 테스트
- Page 실행 속도 개선
<br/>
#98 
<br/>

fix(blueprint): 도면의 검수 여부 기본값 설정

---

server/src/main/java/com/onetool/server/global/redis/controller/TokenController.java

- URL을 slient-refresh로 수정
- 쿠키 키를 refreshToken으로 통일
<br/>
<br/>
#98 
<br/>

fix(auth): silent refresh 수정

---

server/src/main/java/com/onetool/server/global/config/SecurityConfig.java

Spring Security에 silent-refresh 화이트리스트 추가
<br/>
<br/>
#98 
<br/>

fix(auth): silent-refresh 화이트리스트 추가

---

server/src/main/java/com/onetool/server/api/blueprint/controller/BlueprintController.java
server/src/main/java/com/onetool/server/api/blueprint/controller/SearchController.java
server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java
server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java
server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
server/src/test/java/com/onetool/server/category/CategoryServiceTest.java

- close #114 
>메서드 마다가 아닌 클래스에 대한 @transactional 부여
제안해 주신 방법을 통하여  클래스를 분리 후 `BlueprintService`에만 @Trasaction을 부여했습니다.
`BlueprintService`에서 정렬, 검색을 당담하는 매서드를 `BlueprintSearchService`로 이동
`BlueprintController`에서 정렬, 조회에 관련된 컨트롤러를  `SearchController`로 이동
- 매서드 분리 및 컨트롤러 이동으로 인해 변경된 부분을 TEST에도 반영했습니다.
부적절하게 분리가 되었다던가 변경된 코드에 문제가 있는부분 말씀해주세요! 
[Spring AOP self-invocation이 발생하는 이유와 @Transaction 사용시 주의사항](https://woodcock.tistory.com/30)
[[이슈 #1] Spring Transaction의 Self Invocation 이슈](https://yejun-the-developer.tistory.com/13)

fix: BlueprintService의 @Trasaction self-invocation 문제 해결

---

server/src/main/java/com/onetool/server/api/blueprint/controller/BlueprintController.java
server/src/main/java/com/onetool/server/api/blueprint/controller/SearchController.java
server/src/main/java/com/onetool/server/api/blueprint/enums/SortType.java
server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java
server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java

- #113 
BlueprintSearchService에서 SortType에 대한 매핑 메서드를 포함하고 있어요. 이를 SortType enum 클래스 내부에서 처리할 수 있도록 수정했어요.

chore: SortType 매핑을 enum 클래스로 이동

---

server/src/main/java/com/onetool/server/api/member/repository/MemberRepository.java
server/src/main/java/com/onetool/server/global/redis/controller/TokenController.java

- #121 
reissue 응답 형식을 ApiResposne로 변경

fix: reissue 응답 형식을 ApiResposne로 변경

---

server/src/main/java/com/onetool/server/global/auth/AuthService.java

- close #123 
Redis에 Key가 memberId에서 email로 변경됨에 따라 변경되지 않은 로직 수정

fix: RefreshToken 인증 버그 해결

---

server/src/main/java/com/onetool/server/api/blueprint/dto/SearchResponse.java
server/src/main/java/com/onetool/server/api/cart/controller/CartController.java

- close #131 
SearchResponse에 Blueprint가 그대로 들어가 있어, 연관관계인 Cart와 Order에 대한 정보가 조회 쿼리에 담기는 문제를 해결했어요.

fix: SearchResponse 수정

---

server/src/main/resources/application-dev.properties

chore: 토스페이먼츠 api키 임시 등록

---

server/src/main/java/com/onetool/server/DataLoader.java
server/src/main/resources/application-dev.properties

- close #138 
- 테스트 서버 ddl-auto update로 변경
- CommandLineRunner가 데이터 없을 경우에만 데이터를 삽입하도록 수정

chore: 데이터 duplicate 문제 해결

---

server/src/main/java/com/onetool/server/api/cart/controller/CartSessionController.java
server/src/main/java/com/onetool/server/api/cart/dto/CartSessionResponse.java
server/src/main/java/com/onetool/server/api/cart/service/CartSessionService.java

- close #143 
- List를 통해 받은 상품의 ID를 세션에 저장
- 세션에 저장된 모든 상품들을 조회
- 세션에 저장된 상품들 중 일부 상품을 제거
- 세션 자체를 삭제
[spring Boot Session 알아보기](https://chb2005.tistory.com/175)

feat: 세션을 이용한 구매 목록 조회, 추가, 삭제

---

server/src/main/java/com/onetool/server/global/config/SecurityConfig.java

fix: 쿠기 SameSite 속성 변경

---

server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
server/src/main/resources/application.properties

fix: 세션 쿠키 설정 변경

---

server/build.gradle

[build] aws s3 의존성 수정

---

server/build.gradle

Reverts likelion-onetool/backend#150

Revert "[build] aws s3 의존성 수정"

---

server/src/main/java/com/onetool/server/api/order/service/OrderService.java
server/src/main/java/com/onetool/server/api/payments/business/PaymentBusiness.java
server/src/main/java/com/onetool/server/api/payments/controller/PaymentController.java
server/src/main/java/com/onetool/server/api/payments/domain/TossPayment.java
server/src/main/java/com/onetool/server/api/payments/domain/TossPaymentMethod.java
server/src/main/java/com/onetool/server/api/payments/service/PaymentService.java
server/src/main/java/com/onetool/server/global/new_exception/exception/error/PaymentErrorCode.java

- #177 
- paymentBusiness에서 delete를 remove로 변경하여 메서드 명 통일
- OrderService에서 List 반환 시 findAll 메서드 명을 가지도록 통일
- PaymentService에 ApiException 적용

refactor(payment): ApiException을 통한 예외 구조 변경

---

server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintInspectionService.java
server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java
server/src/main/java/com/onetool/server/api/cart/CartBlueprint.java
server/src/main/java/com/onetool/server/api/cart/business/CartBusiness.java
server/src/main/java/com/onetool/server/api/cart/service/CartService.java
server/src/main/java/com/onetool/server/api/member/service/MemberService.java
server/src/main/java/com/onetool/server/api/order/service/OrderService.java
server/src/main/java/com/onetool/server/api/qna/QnaBoard.java
server/src/main/java/com/onetool/server/api/qna/QnaReply.java
server/src/main/java/com/onetool/server/api/qna/service/QnaBoardService.java
server/src/main/java/com/onetool/server/api/qna/service/QnaReplyService.java
server/src/main/java/com/onetool/server/global/generator/RandomGenerator.java
server/src/main/java/com/onetool/server/global/new_exception/exception/error/BlueprintErrorCode.java
server/src/main/java/com/onetool/server/global/new_exception/exception/error/CartErrorCode.java
server/src/main/java/com/onetool/server/global/new_exception/exception/error/OrderErrorCode.java
server/src/main/java/com/onetool/server/global/new_exception/exception/error/QnaErrorCode.java

[refactor: 예외 처리 구조 변경](https://github.com/likelion-onetool/backend/issues/177)#177
- close #이슈번호
해당 issue에 관하여 예외 템플릿이 만들어 진걸 아래 클래스 별로 적용 완료했습니다.
모든 예외처리들을 ApiException으로 통일 시켰습니다.

refactor(qna/cart/blueprint/order): 예외 리팩터링 및 적용

---

server/build.gradle
server/src/main/java/com/onetool/server/api/qna/QnaBoard.java
server/src/main/java/com/onetool/server/api/qna/business/QnaBoardBusiness.java
server/src/main/java/com/onetool/server/api/qna/business/QnaReplyBusiness.java
server/src/main/java/com/onetool/server/api/qna/controller/QnaBoardController.java
server/src/main/java/com/onetool/server/api/qna/controller/QnaReplyController.java
server/src/main/java/com/onetool/server/api/qna/service/QnaBoardService.java
server/src/main/java/com/onetool/server/api/qna/service/QnaReplyService.java
server/src/main/java/com/onetool/server/global/entity/BaseEntity.java
server/src/main/java/com/onetool/server/global/new_exception/exception/ApiException.java
server/src/test/java/com/onetool/server/api/member/fixture/WithMockPrincipalDetailsSecurityContextFactory.java
server/src/test/java/com/onetool/server/api/payments/service/DepositServiceTest.java
server/src/test/java/com/onetool/server/api/qna/business/QnaBoardBusinessTest.java
server/src/test/java/com/onetool/server/api/qna/business/QnaReplyBusinessTest.java
server/src/test/java/com/onetool/server/api/qna/controller/QnaBoardControllerTest.java
server/src/test/java/com/onetool/server/api/qna/controller/QnaReplyControllerTest.java
server/src/test/java/com/onetool/server/api/qna/service/QnaBoardServiceTest.java
server/src/test/java/com/onetool/server/api/qna/service/QnaReplyServiceTest.java
server/src/test/java/com/onetool/server/fixture/MemberFixture.java
server/src/test/java/com/onetool/server/fixture/QnaBoardFixture.java
server/src/test/java/com/onetool/server/fixture/QnaReplyFixture.java

(https://github.com/likelion-onetool/backend/issues/210)
- close #이슈번호
MemberFixture 를 따로 구현 했었습니다.
Mockito 를 이용한 Service 테스트 코드 작성
Mockito 를 이용한 Business 테스트 코드 작성
Mockito 를 이용한 Controller 테스트 코드 작성
@WithMoc~ email도 반환되게 내용 추가했습니다.
@mete0rfish  님이 작성한 테스트 코드를 많이 참고하여 작성했습니다.
추가적으로 MemberFixture 는 일단은 따로 구현했습니다. 
테스트 코드가 전반적으로 일관되고 검증이 잘 되었는지 위주로 봐주시면 감사하겠습니다.
JwtUtil 을 이용하여 SecurityContext에 주입하는 방식으로 제작해 주셨는데 
자세한 구조적 원리가  궁금합니다 : )

test(Qna): Mockito를 이용한 controller - business - service 테스트 작성

---

server/build.gradle
server/src/main/java/com/onetool/server/api/chat/controller/ChatController.java
server/src/main/java/com/onetool/server/api/chat/domain/ChatMessage.java
server/src/main/java/com/onetool/server/api/chat/domain/ChatMessageMongo.java
server/src/main/java/com/onetool/server/api/chat/repository/ChatMongoRepositorySpringImpl.java
server/src/main/java/com/onetool/server/api/chat/repository/ChatMysqlSpringImpl.java
server/src/main/java/com/onetool/server/api/chat/repository/ChatPostgresRepositoryImpl.java
server/src/main/java/com/onetool/server/api/chat/repository/ChatRepository.java
server/src/main/java/com/onetool/server/api/chat/repository/jpa/ChatJpaRepository.java
server/src/main/java/com/onetool/server/api/chat/repository/jpa/ChatPostgresJpaRepository.java
server/src/main/java/com/onetool/server/api/chat/repository/mongo/ChatMongoRepository.java
server/src/main/java/com/onetool/server/api/chat/service/ChatService.java
server/src/main/java/com/onetool/server/data/DataLoader.java
server/src/main/resources/application-local.properties
server/src/main/resources/application.properties
server/src/test/java/com/onetool/server/api/chat/service/ChatServiceTest.java

- close #230
postgress, MongoDB, Mysql 3개 추상화하여 인터페이스를 구현
application.yml 수정 및 build.gradle 추가내용있습니다.

Feat chat 데이터 베이스 3개 추상화하여 테스트 비교 db 구현
